#!/usr/bin/env node
/**
 * One-shot local install for macOS / Windows / Linux:
 *   npm install → npm link → register plugin in OpenCode's plugins folder
 *
 * Usage:
 *   npm run setup
 *   node scripts/setup-local.mjs
 *
 * Options:
 *   --skip-install      Skip npm install (deps already present)
 *   --no-global-cli     Skip npm link (CLI won't be global)
 *   --copy              Stub loader (no symlink). Writes a tiny file that imports the repo entry — safe on Windows without symlink rights.
 *
 * Env:
 *   OPENCODE_PLUGINS_DIR  Override plugins directory (absolute path)
 */

import { spawnSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import { fileURLToPath, pathToFileURL } from 'url';
import os from 'os';
import chalk from 'chalk';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const ENTRY = path.join(ROOT, 'src', 'index.js');

function usage() {
  console.log(`
${chalk.bold('opencode-figma — local setup')}

  npm run setup

  Options:
    --skip-install     Skip npm install
    --no-global-cli    Skip npm link (no global opencode-figma command)
    --copy             Copy plugin file instead of symlink

  Env:
    OPENCODE_PLUGINS_DIR   Custom OpenCode plugins directory

${chalk.gray('  © 2026 M.Milde <m.milde@gmail.com>')}
`);
}

function openCodePluginsDir() {
  if (process.env.OPENCODE_PLUGINS_DIR) {
    return path.resolve(process.env.OPENCODE_PLUGINS_DIR);
  }
  if (process.platform === 'win32') {
    const appData =
      process.env.APPDATA || path.join(os.homedir(), 'AppData', 'Roaming');
    return path.join(appData, 'opencode', 'plugins');
  }
  return path.join(os.homedir(), '.config', 'opencode', 'plugins');
}

function opencodeFigmaDir() {
  return path.join(os.homedir(), '.opencode-figma');
}

function ensureDir(p) {
  fs.mkdirSync(p, { recursive: true });
}

function writeJsonIfMissing(filePath, value) {
  try {
    if (fs.existsSync(filePath)) return false;
    ensureDir(path.dirname(filePath));
    fs.writeFileSync(filePath, JSON.stringify(value, null, 2), 'utf8');
    return true;
  } catch {
    return false;
  }
}

function runNodeCli(args, { timeoutMs = 90000 } = {}) {
  // Use node directly to avoid shebang issues on Windows.
  const node = process.execPath;
  const cli = path.join(ROOT, 'bin', 'opencode-figma');
  return spawnSync(node, [cli, ...args], {
    cwd: ROOT,
    stdio: 'inherit',
    timeout: timeoutMs,
    shell: false
  });
}

/**
 * Remove a file or symlink at linkPath so we can recreate it.
 *
 * IMPORTANT (Windows): `fs.existsSync` follows symlinks. A symlink whose target no
 * longer exists (moved repo, wrong drive, OneDrive) reports "missing", so callers
 * that skip unlink when existsSync is false leave a dangling reparse point behind.
 * The next symlink attempt then fails with EEXIST; writing through the symlink can
 * throw ENOENT. Always use `lstatSync` and unlink the link itself — do not rely on existsSync.
 */
function removeEntry(linkPath) {
  try {
    const st = fs.lstatSync(linkPath);
    if (st.isDirectory()) {
      throw new Error(`Refusing to remove directory at ${linkPath} — delete it manually.`);
    }
    fs.unlinkSync(linkPath);
  } catch (e) {
    if (e && e.code === 'ENOENT') return;
    throw e;
  }
}

/**
 * When symlinks are unavailable (typical Windows without Developer Mode),
 * copying src/index.js into plugins breaks relative imports and ../bin resolution.
 * Instead write a stub that re-exports from the real file URL.
 */
function writePluginStub(linkPath, entryAbs) {
  removeEntry(linkPath);
  const entryUrl = pathToFileURL(path.resolve(entryAbs)).href;
  const lines = [
    '// Generated by opencode-figma `npm run setup` — do not edit.',
    '// Loads the plugin from your repo so imports and CLI path resolve correctly.',
    `export { default, OpenCodeFigmaPlugin } from ${JSON.stringify(entryUrl)};\n`
  ];
  fs.writeFileSync(linkPath, lines.join('\n'), 'utf8');
}

async function main() {
  const argv = process.argv.slice(2);
  if (argv.includes('-h') || argv.includes('--help')) {
    usage();
    process.exit(0);
  }

  const skipInstall = argv.includes('--skip-install');
  const noGlobalCli = argv.includes('--no-global-cli');
  const copyOnly = argv.includes('--copy');
  const noConnect = argv.includes('--no-connect');

  console.log(chalk.hex('#FF6B35')('\n  opencode-figma') + chalk.white(' — local install'));
  console.log(chalk.gray('  © 2026 M.Milde <m.milde@gmail.com>\n'));

  if (!fs.existsSync(ENTRY)) {
    console.error(chalk.red(`Missing ${ENTRY} — run this script from the repo root.`));
    process.exit(1);
  }

  if (!skipInstall) {
    console.log(chalk.cyan('→ npm install'));
    const shell = process.platform === 'win32';
    const r = spawnSync('npm', ['install'], {
      cwd: ROOT,
      stdio: 'inherit',
      shell
    });
    if (r.status !== 0 && r.status != null) process.exit(r.status);
  }

  if (!noGlobalCli) {
    console.log(chalk.cyan('→ npm link') + chalk.gray(' (global CLI: opencode-figma)'));
    const shell = process.platform === 'win32';
    const r = spawnSync('npm', ['link'], { cwd: ROOT, stdio: 'inherit', shell });
    if (r.status !== 0 && r.status != null) {
      console.log(
        chalk.yellow(
          '⚠ npm link failed — add npm global bin to PATH, or run CLI via:'
        )
      );
      console.log(chalk.gray(`    node ${path.join(ROOT, 'bin', 'opencode-figma')} …`));
    }
  }

  const pluginsDir = openCodePluginsDir();
  const linkPath = path.join(pluginsDir, 'opencode-figma.js');

  fs.mkdirSync(pluginsDir, { recursive: true });
  console.log(chalk.cyan('→ OpenCode plugins dir: ') + chalk.white(pluginsDir));

  try {
    removeEntry(linkPath);
  } catch (e) {
    console.error(chalk.red(e.message));
    process.exit(1);
  }

  const targetAbs = path.resolve(ENTRY);

  if (copyOnly) {
    writePluginStub(linkPath, targetAbs);
    console.log(
      chalk.green(`✓ Stub loader`) +
        chalk.gray(` → ${path.basename(linkPath)} (imports repo entry)`)
    );
    console.log(
      chalk.gray('  Re-run ') +
        chalk.cyan('npm run setup') +
        chalk.gray(' if you move the repo or after major path changes.')
    );
  } else {
    try {
      fs.symlinkSync(targetAbs, linkPath, 'file');
      console.log(chalk.green(`✓ Symlink`) + chalk.gray(` → ${linkPath}`));
    } catch (e) {
      fallbackCopy(targetAbs, linkPath, e);
    }
  }

  console.log(chalk.cyan('\n→ Verifying plugin…'));
  const href = pathToFileURL(linkPath).href;
  try {
    const m = await import(href);
    const factory = m.default ?? m.OpenCodeFigmaPlugin;
    if (typeof factory !== 'function') {
      throw new Error('Plugin module has no default export');
    }
    const p = await factory({});
    const tools = Object.keys(p.tool || {});
    console.log(
      chalk.green(`✓ Loaded ${tools.length} tools`) +
        chalk.gray(` (${p.name} ${p.version})`)
    );

    // ------------------------------------------------------------
    // Zero-input defaults (CDP + selection-friendly targeting)
    // ------------------------------------------------------------
    const cfgDir = opencodeFigmaDir();
    const settingsFile = path.join(cfgDir, 'settings.json');
    const wrote = writeJsonIfMissing(settingsFile, { strict: false });
    console.log(
      chalk.cyan('→ Plugin settings: ') +
        chalk.white(settingsFile) +
        chalk.gray(wrote ? ' (created)' : ' (exists)')
    );

    // ------------------------------------------------------------
    // Best-effort connect smoke test (optional)
    // ------------------------------------------------------------
    let ready = true;
    let readyReason = '';
    if (!noConnect) {
      console.log(chalk.cyan('\n→ Connecting to Figma (best-effort)…'));
      const cr = runNodeCli(['connect'], { timeoutMs: 180000 });
      if (cr.status === 0) {
        console.log(chalk.green('✓ Connected to Figma (CDP ready)'));
      } else {
        ready = false;
        readyReason = 'connect failed (open any Figma file tab once, then rerun setup)';
        console.log(chalk.yellow('⚠ Could not complete auto-connect.'));
        console.log(
          chalk.gray(
            '  This is usually because no design file tab is open yet.\n' +
              '  Do this once: open Figma Desktop → open any file (canvas tab), then re-run:\n' +
              '    npm run setup\n'
          )
        );
      }
    }

    console.log(chalk.gray('\nNext: open OpenCode, then run ') + chalk.white('figma_connect') + chalk.gray(' (or:\n'));
    console.log(chalk.white('  opencode-figma connect'));
    console.log(chalk.gray('  © 2026 M.Milde <m.milde@gmail.com>\n'));

    // Machine-readable final status line (for docs/CI/log parsing).
    if (ready) {
      console.log('READY');
    } else {
      console.log(`NOT READY: ${readyReason || 'unknown'}`);
      process.exitCode = 1;
    }
  } catch (err) {
    console.error(chalk.red('✗ Verify failed:'), err.message);
    process.exit(1);
  }
}

function fallbackCopy(targetAbs, linkPath, err) {
  console.log(
    chalk.yellow(`⚠ Symlink not available (${err.code || err.message})`)
  );
  console.log(
    chalk.gray(
      '  Using stub loader (imports repo entry). For symlinks: Windows Developer Mode or admin.'
    )
  );
  writePluginStub(linkPath, targetAbs);
  console.log(chalk.green(`✓ Stub loader`) + chalk.gray(` → ${linkPath}`));
  console.log(
    chalk.gray('  Re-run ') + chalk.cyan('npm run setup') + chalk.gray(' after git pull or if you move the repo.')
  );
}

main().catch((e) => {
  console.error(chalk.red(e.message || e));
  process.exit(1);
});
